"""empty message

Revision ID: 011e02fda3ad
Revises: dc69d8d36b51
Create Date: 2021-06-19 21:26:33.683463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011e02fda3ad'
down_revision = 'dc69d8d36b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modules_etudiant_id_fkey', 'modules', type_='foreignkey')
    op.drop_column('modules', 'etudiant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('modules_etudiant_id_fkey', 'modules', 'etudiants', ['etudiant_id'], ['id'])
    # ### end Alembic commands ###
