"""empty message

Revision ID: 14a71c9a166d
Revises: 1f5da7f44ef9
Create Date: 2021-06-15 23:52:00.179242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a71c9a166d'
down_revision = '1f5da7f44ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('matricule', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'etudiants', ['matricule'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etudiants', type_='unique')
    op.drop_column('etudiants', 'matricule')
    # ### end Alembic commands ###
