"""empty message

Revision ID: 1b9638ab2587
Revises: 011e02fda3ad
Create Date: 2021-06-19 22:38:06.516759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9638ab2587'
down_revision = '011e02fda3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('etudiant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules', 'etudiants', ['etudiant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'etudiant_id')
    # ### end Alembic commands ###
