"""empty message

Revision ID: 1f5da7f44ef9
Revises: b8f762bf3548
Create Date: 2021-06-15 23:47:30.167115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5da7f44ef9'
down_revision = 'b8f762bf3548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('matricule', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'matricule')
    # ### end Alembic commands ###
