"""empty message

Revision ID: 25e122ecc70a
Revises: 312eabcec953
Create Date: 2021-07-03 22:46:51.244263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e122ecc70a'
down_revision = '312eabcec953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module')
    op.drop_constraint('moyenne_module_id_fkey', 'moyenne', type_='foreignkey')
    op.drop_column('moyenne', 'module_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moyenne', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('moyenne_module_id_fkey', 'moyenne', 'module', ['module_id'], ['id'])
    op.create_table('module',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='modules_pkey'),
    sa.UniqueConstraint('name', name='modules_name_key')
    )
    # ### end Alembic commands ###
