"""empty message

Revision ID: 312eabcec953
Revises: 4e72f7bf0cc8
Create Date: 2021-07-03 18:28:49.614524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312eabcec953'
down_revision = '4e72f7bf0cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'choix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('choix', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
