"""empty message

Revision ID: 5c6e30dce8f6
Revises: 96329c36bdee
Create Date: 2021-06-24 18:19:11.643983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c6e30dce8f6'
down_revision = '96329c36bdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moyenne')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moyenne',
    sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moyenne', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], name='moyenne_etudiant_id_fkey'),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name='moyenne_module_id_fkey'),
    sa.PrimaryKeyConstraint('etudiant_id', 'module_id', name='moyenne_pkey')
    )
    # ### end Alembic commands ###
