"""empty message

Revision ID: 5f3ea6ee07f7
Revises: 845fdaaf0cc9
Create Date: 2021-04-18 18:11:07.111369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3ea6ee07f7'
down_revision = '845fdaaf0cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_at')
    # ### end Alembic commands ###
