"""empty message

Revision ID: 88a12dc9ab52
Revises: 3c34c56ef398
Create Date: 2021-06-14 18:16:45.290045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a12dc9ab52'
down_revision = '3c34c56ef398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moyenne', sa.Column('moyenne', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moyenne', 'moyenne')
    # ### end Alembic commands ###
