"""empty message

Revision ID: 96329c36bdee
Revises: fb628c4cf2d0
Create Date: 2021-06-22 00:42:16.328590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96329c36bdee'
down_revision = 'fb628c4cf2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'matricule',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'matricule',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
