"""empty message

Revision ID: 9f16e0d64198
Revises: 198a70c16cb2
Create Date: 2021-06-15 01:54:00.050422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f16e0d64198'
down_revision = '198a70c16cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'etudiant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'etudiant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
