"""empty message

Revision ID: b8f762bf3548
Revises: d89cd458dabb
Create Date: 2021-06-15 23:46:45.536943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f762bf3548'
down_revision = 'd89cd458dabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('etudiants_matricule_key', 'etudiants', type_='unique')
    op.drop_column('etudiants', 'matricule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('matricule', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('etudiants_matricule_key', 'etudiants', ['matricule'])
    # ### end Alembic commands ###
