"""empty message

Revision ID: d305c411b15a
Revises: 006fc631e194
Create Date: 2021-06-20 14:35:04.501335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd305c411b15a'
down_revision = '006fc631e194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moyenne',
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'module_id')
    )
    op.drop_table('moyennes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moyennes',
    sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moyenne', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], name='moyennes_etudiant_id_fkey'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name='moyennes_module_id_fkey')
    )
    op.drop_table('moyenne')
    # ### end Alembic commands ###
