"""empty message

Revision ID: d89cd458dabb
Revises: 9f16e0d64198
Create Date: 2021-06-15 16:40:40.002402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89cd458dabb'
down_revision = '9f16e0d64198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('etudiants_email_key', 'etudiants', type_='unique')
    op.drop_constraint('etudiants_phone_key', 'etudiants', type_='unique')
    op.drop_column('etudiants', 'phone')
    op.drop_column('etudiants', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('etudiants', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('etudiants_phone_key', 'etudiants', ['phone'])
    op.create_unique_constraint('etudiants_email_key', 'etudiants', ['email'])
    # ### end Alembic commands ###
