"""empty message

Revision ID: e4dc99b28337
Revises: 14a71c9a166d
Create Date: 2021-06-16 00:07:23.963221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4dc99b28337'
down_revision = '14a71c9a166d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('matricule', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'etudiants', ['matricule'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etudiants', type_='unique')
    op.drop_column('etudiants', 'matricule')
    # ### end Alembic commands ###
