"""empty message

Revision ID: e7161f611835
Revises: 1b9638ab2587
Create Date: 2021-06-19 22:47:04.581023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7161f611835'
down_revision = '1b9638ab2587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moyenne', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('moyenne_etudiant_id_fkey', 'moyenne', type_='foreignkey')
    op.drop_constraint('moyenne_module_id_fkey', 'moyenne', type_='foreignkey')
    op.drop_column('moyenne', 'module_id')
    op.drop_column('moyenne', 'etudiant_id')
    op.drop_column('moyenne', 'moyenne')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moyenne', sa.Column('moyenne', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('moyenne', sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('moyenne', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('moyenne_module_id_fkey', 'moyenne', 'modules', ['module_id'], ['id'])
    op.create_foreign_key('moyenne_etudiant_id_fkey', 'moyenne', 'etudiants', ['etudiant_id'], ['id'])
    op.drop_column('moyenne', 'id')
    # ### end Alembic commands ###
