"""empty message

Revision ID: eed407d9bdb8
Revises: 
Create Date: 2021-06-20 21:34:24.108856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eed407d9bdb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moyennes')
    op.drop_constraint('modules_etudiant_id_fkey', 'module', type_='foreignkey')
    op.drop_column('module', 'etudiant_id')
    op.add_column('moyenne', sa.Column('moyenne', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moyenne', 'moyenne')
    op.add_column('module', sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('modules_etudiant_id_fkey', 'module', 'etudiants', ['etudiant_id'], ['id'])
    op.create_table('moyennes',
    sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moyenne', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], name='moyennes_etudiant_id_fkey'),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name='moyennes_module_id_fkey'),
    sa.PrimaryKeyConstraint('etudiant_id', 'module_id', name='moyennes_pkey')
    )
    # ### end Alembic commands ###
